"""Configuration management with pydantic-settings"""

import os
from pathlib import Path
from typing import Any, List, Optional, Tuple

from platformdirs import user_config_dir, user_data_dir
from pydantic import Field
from pydantic_settings import (
    BaseSettings,
    PydanticBaseSettingsSource,
    SettingsConfigDict,
    YamlConfigSettingsSource,
)

DEFAULT_CONFIG_DIR = Path(user_config_dir("kiwix-llm-cli"))
DEFAULT_CONFIG_FILE = DEFAULT_CONFIG_DIR / "config.yaml"
DEFAULT_DATA_DIR = Path(user_data_dir("kiwix-llm-cli"))
LOCAL_CONFIG_FILE = Path.cwd() / ".kiwix-llm-cli.yaml"

ENV_CONFIG_FILE = "KWXLC_CONFIG_FILE"
ENV_IGNORE_CONFIG = "KWXLC_IGNORE_CONFIG"


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_prefix="KWXLC_",
        env_nested_delimiter="__",
        extra="ignore",
    )

    default_zim: Optional[str] = None
    backend: str = "libzim"
    kiwix_api_url: str = "http://localhost:8080"
    search_dirs: List[str] = Field(default_factory=lambda: [str(DEFAULT_DATA_DIR)])
    download_dir: str = Field(default_factory=lambda: str(DEFAULT_DATA_DIR))

    @classmethod
    def find_local_config(cls) -> Optional[Path]:
        local_config = Path.cwd() / ".kiwix-llm-cli.yaml"
        if local_config.exists():
            return local_config
        return None

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: type[BaseSettings],
        init_settings: PydanticBaseSettingsSource,
        env_settings: PydanticBaseSettingsSource,
        dotenv_settings: PydanticBaseSettingsSource,
        file_secret_settings: PydanticBaseSettingsSource,
    ) -> Tuple[PydanticBaseSettingsSource, ...]:
        if os.getenv(ENV_IGNORE_CONFIG):
            return (init_settings, env_settings)

        config_from_env = os.getenv(ENV_CONFIG_FILE)
        if config_from_env:
            yaml_file = Path(config_from_env)
            if yaml_file.exists():
                return (
                    init_settings,
                    env_settings,
                    YamlConfigSettingsSource(settings_cls, yaml_file=yaml_file),
                )

        sources: List[PydanticBaseSettingsSource] = [
            init_settings,
            env_settings,
        ]

        local = cls.find_local_config()
        if local:
            sources.append(YamlConfigSettingsSource(settings_cls, yaml_file=local))

        if DEFAULT_CONFIG_FILE.exists():
            sources.append(
                YamlConfigSettingsSource(settings_cls, yaml_file=DEFAULT_CONFIG_FILE)
            )

        return tuple(sources)

    @classmethod
    def load(
        cls,
        config_path: Optional[Path] = None,
        ignore_config: bool = False,
    ) -> "Settings":
        if ignore_config:
            os.environ[ENV_IGNORE_CONFIG] = "1"
        if config_path:
            os.environ[ENV_CONFIG_FILE] = str(config_path)
        return cls()

    def get_search_dirs(self) -> List[Path]:
        dirs: List[Path] = []
        for d in self.search_dirs:
            path = Path(d.replace("~", str(Path.home())))
            if path.exists():
                dirs.append(path)
        return dirs

    def get_download_dir(self) -> Path:
        return Path(self.download_dir.replace("~", str(Path.home())))

    def get_kiwix_api_url(self) -> str:
        return self.kiwix_api_url.replace("~", str(Path.home()))


def dump_config(settings: Settings, output: Optional[Path] = None) -> str:
    import yaml

    def str_presenter(dumper: yaml.Dumper, data: str) -> Any:
        if len(data.splitlines()) > 1:
            return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
        return dumper.represent_scalar("tag:yaml.org,2002:str", data)

    yaml.add_representer(str, str_presenter)

    config_dict = settings.model_dump()

    header = """# kiwix-llm-cli Configuration
# Generated by kiwix-llm-cli (kwxlc)

# Settings:
# - default_zim: Default ZIM file name (auto-detected name)
# - backend: Default backend (libzim or api)
# - kiwix_api_url: URL for kiwix-serve API endpoint
# - search_dirs: Directories to search for ZIM files (auto-discovery)
# - download_dir: Directory for downloaded ZIM files

"""

    yaml_text = yaml.dump(
        config_dict,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
    )

    final_output = header + yaml_text

    if output:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(final_output, encoding="utf-8")
        return str(output)

    return final_output


def create_default_config(output: Optional[Path] = None) -> str:
    settings = Settings.load(ignore_config=True)
    return dump_config(settings, output)
